Redisign transcript results column and add detail transcript page
askpradana/frontend-transcript-adauntukkamu pull request #10
Opened 2024-11-05 06:44 UTC by rizalyoga

2024-11-05 07:41 UTC, askpradana commented on src/utils/utils.ts
kita pake format id aja cuy, buat sekarang targetnya orang lokal dulu, next bae

2024-11-05 08:05 UTC, askpradana requested changes
pakai format lokal id bae

2024-11-05 21:54 UTC, rizalyoga commented on src/utils/utils.ts
okay

2024-11-06 03:35 UTC, askpradana approved these changes

2024-11-06 03:35 UTC, merged